### ISSUE TITLE
Missing types, can't even build them with electron-rebuild

### ISSUE THREAD

**Issue by studentutu** [iishiishii/opencv#2]
Good evening, I 've stumbled upon this package, as it it ideal for electron, but there is an issue with missing types.

Can you generate them and release an updated packages with all the types?

Electron rebuild doesn't work by default, so we can't even use it effectively(

**Comment by studentutu** [comment]
found out you just need to update index.d.ts as follows ( it will export all types from underlying OpenCV without any additional hassle)
```
import type * as openCV from './types/';
export type * as openCV from './types/';

/**
 * OpenCV Object
 */
export declare const cv: typeof openCV;
```

**Comment by studentutu** [comment]
feel free to close this issue when you are done!

**Comment by studentutu** [comment]
also, please update package to include pre-build types, as we can;t build it - folder utils is ignored and not present in node_modules/opencv-web

**Comment by iishiishii** [comment]
Thanks @studentutu for suggesting the solution. Please test the latest version 4.9.0-1 if it works for you :)

**Comment by studentutu** [comment]
works, thanks!
